In [24]:
import pandas as pd
import os

In [16]:
albania_raw = pd.read_csv("/Users/grealish/Desktop/Euros Prediction Model/EuroPrediction/Game Statistics/Albania_ALL.csv", encoding='latin1')

In [17]:
albania_raw

,Team,Game Link,Ball possession,Expected goals,Big chances,Total shots,Goalkeeper saves,Corner kicks,Fouls,Passes,...,Tackles won,Total tackles,Interceptions,Recoveries,Clearances,Goals prevented,Goalkeeper saves.1,Goal kicks,Goals,Date
0,Moldova,https://www.sofascore.com/moldova-albania/PTbs...,47%,No information,1,13,3,4,22,405,...,57%,14,5,50,6,No information,3,4,1,"17/11/2023, 09:00"
1,Albania,https://www.sofascore.com/moldova-albania/PTbs...,53%,No information,1,10,5,2,18,467,...,85%,13,5,57,23,No information,5,3,1,"17/11/2023, 09:00"
2,Albania,https://www.sofascore.com/faroe-islands-albani...,64%,No information,1,8,0,2,6,641,...,73%,15,3,60,19,No information,0,6,0,"20/11/2023, 11:45"
3,Faroe islands,https://www.sofascore.com/faroe-islands-albani...,36%,No information,0,10,4,3,17,360,...,52%,21,10,63,22,No information,4,5,0,"20/11/2023, 11:45"
4,Albania,https://www.sofascore.com/chile-albania/PTbseV...,55%,No information,0,7,1,4,9,585,...,50%,14,9,42,11,No information,1,7,3,"22/03/2024, 12:45"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Albania,https://www.sofascore.com/andorra-albania/PTbs...,25%,No information,0,9,4,4,18,187,...,60%,10,9,No information,40,No information,4,14,0,"25/03/2019, 12:45"
84,Albania,https://www.sofascore.com/turkey-albania/PTbsa...,59%,No information,2,15,4,3,20,541,...,80%,15,11,No information,10,No information,4,4,2,"22/03/2019, 12:45"
85,Türkiye,https://www.sofascore.com/turkey-albania/PTbsa...,41%,No information,1,8,5,1,21,367,...,79%,14,14,No information,15,No information,5,12,0,"22/03/2019, 12:45"
86,Albania,https://www.sofascore.com/belarus-albania/PTbs...,45%,No information,3,10,2,9,12,385,...,65%,17,15,No information,22,No information,2,6,3,"18/11/2020, 07:00"
87,Belarus,https://www.sofascore.com/belarus-albania/PTbs...,55%,No information,3,11,1,6,16,480,...,59%,17,16,No information,18,No information,1,5,2,"18/11/2020, 07:00"

In [18]:
list(albania_raw.columns)

['Team',
 'Game Link',
 'Ball possession',
 'Expected goals',
 'Big chances',
 'Total shots',
 'Goalkeeper saves',
 'Corner kicks',
 'Fouls',
 'Passes',
 'Tackles',
 'Free kicks',
 'Yellow cards',
 'Red cards',
 'Shots on target',
 'Hit woodwork',
 'Shots off target',
 'Blocked shots',
 'Shots inside box',
 'Shots outside box',
 'Big chances scored',
 'Big chances missed',
 'Through balls',
 'Touches in penalty area',
 'Fouled in final third',
 'Offsides',
 'Accurate passes',
 'Throw-ins',
 'Final third entries',
 'Long balls',
 'Crosses',
 'Duels',
 'Dispossessed',
 'Ground duels',
 'Aerial duels',
 'Dribbles',
 'Tackles won',
 'Total tackles',
 'Interceptions',
 'Recoveries',
 'Clearances',
 'Goals prevented',
 'Goalkeeper saves.1',
 'Goal kicks',
 'Goals',
 'Date']

In [23]:
# Team,Ball possession,Big chances,Total shots,Goalkeeper saves,Corner kicks,Fouls,Passes,Tackles,Free kicks,Yellow cards,Red cards,Shots on target,Hit woodwork,Shots off target,Blocked shots,Shots inside box,Shots outside box,Big chances scored,Big chances missed,Through balls,Touches in penalty area,Fouled in final third,Offsides,Accurate passes,Throw-ins,Final third entries,Long balls,Crosses,Duels,Dispossessed,Ground duels,Aerial duels,Dribbles,Tackles won,Total tackles,Interceptions,Recoveries,Clearances,Goals prevented,Goalkeeper saves,Goal kicks,Goals


# combining the game stats into one row

def combine_game_stats(file_path, target_team, output_file):
    stat_columns =  stat_columns = ['Ball possession', 'Big chances', 'Total shots', 'Goalkeeper saves', 'Corner kicks', 'Fouls',
                    'Passes', 'Tackles', 'Free kicks', 'Yellow cards', 'Red cards', 'Shots on target', 
                    'Hit woodwork', 'Shots off target', 'Blocked shots', 'Shots inside box', 'Shots outside box', 
                    'Big chances scored', 'Big chances missed', 'Through balls', 'Touches in penalty area', 
                    'Fouled in final third', 'Offsides', 'Accurate passes', 'Throw-ins', 'Final third entries', 
                    'Long balls', 'Crosses', 'Duels', 'Dispossessed', 'Ground duels', 'Aerial duels', 'Dribbles', 
                    'Tackles won', 'Total tackles', 'Interceptions', 'Recoveries', 'Clearances', 'Goals prevented', 
                    'Goalkeeper saves', 'Goal kicks', 'Goals']
    df = pd.read_csv(file_path, encoding ='latin1')
    grouped= df.groupby('Game Link')

    combined_data = []
    for game_link, group in grouped:
        if len(group) == 2:
            team1, team2 = group.iloc[0], group.iloc[1]

            if team1['Team'] == target_team:
                target_row = team1
                opponent_row = team2
            else:
                target_row = team2
                opponent_row = team1
            combined_row = {'Game Link': game_link,
                            'Target Team': target_row['Team'],
                            'Opponent': opponent_row['Team'],
                            'Date': target_row['Date'],}
            for col in stat_columns:
                combined_row[f'{col} For'] = target_row[col]
                combined_row[f'{col} Against'] = opponent_row[col]
            combined_data.append(combined_row)
        combined_df = pd.DataFrame(combined_data)
        combined_df.to_csv(output_file,index = False)
    return combined_df

file_path = '/Users/grealish/Desktop/Euros Prediction Model/EuroPrediction/Game Statistics/Albania_ALL.csv' 
output_file = '/Users/grealish/Desktop/Euros Prediction Model/EuroPrediction/Game Stats Cleaned/Albania_Combined_Performance.csv'  
target_team = 'Albania'

combined_df = combine_game_stats(file_path, target_team, output_file)

combined_df

,Game Link,Target Team,Opponent,Date,Ball possession For,Ball possession Against,Big chances For,Big chances Against,Total shots For,Total shots Against,...,Recoveries For,Recoveries Against,Clearances For,Clearances Against,Goals prevented For,Goals prevented Against,Goal kicks For,Goal kicks Against,Goals For,Goals Against
0,https://www.sofascore.com/albania-israel/FObsP...,Albania,Israel,"10/06/2022, 11:45",51%,49%,3,1,14,9,...,No information,No information,24,15,No information,No information,3,17,2,1
1,https://www.sofascore.com/albania-israel/FObsP...,Albania,Israel,"24/09/2022, 11:45",49%,51%,1,3,9,14,...,No information,No information,15,24,No information,No information,17,3,1,2
2,https://www.sofascore.com/albania-sweden/NTbsP...,Albania,Sweden,"25/03/2024, 11:00",49%,51%,1,1,8,11,...,54,53,16,12,No information,No information,10,9,0,1
3,https://www.sofascore.com/andorra-albania/PTbs...,Albania,Andorra,"25/03/2019, 12:45",25%,75%,0,5,9,19,...,No information,No information,40,9,No information,No information,14,7,0,3
4,https://www.sofascore.com/andorra-albania/PTbs...,Albania,Andorra,"25/03/2021, 12:45",25%,75%,0,5,9,19,...,No information,No information,40,9,No information,No information,14,7,0,1
5,https://www.sofascore.com/andorra-albania/PTbs...,Albania,Andorra,"15/11/2021, 11:45",75%,25%,5,0,19,9,...,No information,No information,9,40,No information,No information,7,14,1,0
6,https://www.sofascore.com/armenia-albania/PTbs...,Albania,Armenia,"19/11/2022, 08:30",48%,52%,No information,No information,9,11,...,No information,No information,No information,No information,No information,No information,15,8,2,0
7,https://www.sofascore.com/azerbaijan-albania/P...,Albania,Azerbaijan,"07/06/2024, 10:00",40%,60%,No information,No information,11,9,...,No information,No information,No information,No information,No information,No information,10,6,3,1
8,https://www.sofascore.com/belarus-albania/PTbs...,Albania,Belarus,"04/09/2020, 11:45",55%,45%,3,3,11,10,...,No information,No information,18,22,No information,No information,5,6,0,2
9,https://www.sofascore.com/belarus-albania/PTbs...,Albania,Belarus,"18/11/2020, 07:00",45%,55%,3,3,10,11,...,No information,No information,22,18,No information,No information,6,5,3,2
10,https://www.sofascore.com/bulgaria-albania/PTb...,Albania,Bulgaria,"17/10/2023, 09:00",60%,40%,No information,No information,9,6,...,No information,No information,No information,No information,No information,No information,9,4,2,0
11,https://www.sofascore.com/chile-albania/PTbseV...,Albania,Chile,"22/03/2024, 12:45",55%,45%,0,1,7,9,...,42,45,11,11,No information,No information,7,7,3,0
12,https://www.sofascore.com/croatia-albania/PTbs...,Albania,Croatia,"19/06/2024, 06:00",33%,67%,4,4,15,22,...,57,60,26,7,0.92,0.43,11,4,2,2
13,https://www.sofascore.com/czech-republic-alban...,Albania,Czechia,"07/09/2023, 11:45",43%,57%,0,3,1,12,...,63,74,25,8,No information,No information,12,6,1,1
14,https://www.sofascore.com/czech-republic-alban...,Albania,Czechia,"12/10/2023, 11:45",36%,64%,2,0,8,13,...,69,61,38,4,No information,No information,7,5,3,0
15,https://www.sofascore.com/england-albania/PTbs...,Albania,England,"28/03/2021, 09:00",64%,36%,4,1,15,5,...,No information,No information,4,16,No information,No information,0,12,2,0
16,https://www.sofascore.com/england-albania/PTbs...,Albania,England,"12/11/2021, 11:45",36%,64%,1,4,5,15,...,No information,No information,16,4,No information,No information,12,0,0,5
17,https://www.sofascore.com/estonia-albania/PTbs...,Albania,Estonia,"13/06/2022, 09:00",57%,43%,No information,No information,6,1,...,No information,No information,No information,No information,No information,No information,6,10,0,0
18,https://www.sofascore.com/faroe-islands-albani...,Albania,Faroe islands,"20/06/2023, 11:45",36%,64%,0,1,10,8,...,63,60,22,19,No information,No information,5,6,1,3
19,https://www.sofascore.com/faroe-islands-albani...,Albania,Faroe islands,"20/11/2023, 11:45",64%,36%,1,0,8,10,...,60,63,19,22,No information,No information,6,5,0,0
20,https://www.sofascore.com/georgia-albania/PTbs...,Albania,Georgia,"29/03/2022, 09:00",54%,46%,No information,No information,15,5,...,No information,No information,No information,No information,No information,No information,4,10,0,0
21,https://www.sofascore.com/hungary-albania/PTbs...,Albania,Hungary,"05/09/2021, 09:00",64%,36%,2,2,7,9,...,No information,No information,17,15,No information,No information,3,5,1,0
22,https://www.sofascore.com/hungary-albania/PTbs...,Albania,Hungary,"09/10/2021, 11:45",36%,64%,2,2,9,7,...,No information,No information,15,17,No information,No information,5,3,0,1
23,https://www.sofascore.com/iceland-albania/PTbs...,Albania,Iceland,"06/06/2022, 11:45",38%,62%,1,2,8,21,...,No information,No information,32,9,No information,No information,6,7,1,1
24,https://www.sofascore.com/iceland-albania/PTbs...,Albania,Iceland,"27/09/2022, 11:45",62%,38%,2,1,21,8,...,No information,No information,9,32,No information,No information,7,6,1,1
25,https://www.sofascore.com/italy-albania/PTbshU...,Albania,Italy,"16/11/2022, 11:45",68%,32%,5,2,17,8,...,37,32,6,15,-0.41,-0.41,3,8,3,1
26,https://www.sofascore.com/italy-albania/PTbshU...,Albania,Italy,"15/06/2024, 12:00",32%,68%,2,5,8,17,...,32,37,15,6,-0.41,-0.41,8,3,1,2
27,https://www.sofascore.com/kazakhstan-albania/P...,Albania,Kazakhstan,"11/10/2020, 06:00",40%,60%,2,5,12,18,...,No information,No information,17,11,No information,No information,5,4,0,0
28,https://www.sofascore.com/kazakhstan-albania/P...,Albania,Kazakhstan,"15/11/2020, 09:00",60%,40%,5,2,18,12,...,No information,No information,11,17,No information,No information,4,5,3,1
29,https://www.sofascore.com/liechtenstein-albani...,Albania,Liechtenstein,"03/06/2024, 11:00",No information,No information,No information,No information,14,0,...,No information,No information,No information,No information,No information,No information,0,12,3,0
30,https://www.sofascore.com/lithuania-albania/PT...,Albania,Lithuania,"07/09/2020, 11:45",39%,61%,0,2,7,14,...,No information,No information,40,6,No information,No information,12,11,1,0
31,https://www.sofascore.com/lithuania-albania/PT...,Albania,Lithuania,"14/10/2020, 09:00",61%,39%,2,0,14,7,...,No information,No information,6,40,No information,No information,11,12,0,0
32,https://www.sofascore.com/moldova-albania/PTbs...,Albania,Moldova,"17/06/2023, 11:45",47%,53%,1,1,13,10,...,50,57,6,23,No information,No information,4,3,2,0
33,https://www.sofascore.com/moldova-albania/PTbs...,Albania,Moldova,"17/11/2023, 09:00",53%,47%,1,1,10,13,...,57,50,23,6,No information,No information,3,4,1,1
34,https://www.sofascore.com/poland-albania/PTbsd...,Albania,Poland,"27/03/2023, 11:45",61%,39%,1,1,12,7,...,65,68,7,35,No information,No information,5,11,0,1
35,https://www.sofascore.com/poland-albania/PTbsd...,Albania,Poland,"10/09/2023, 11:45",39%,61%,1,1,7,12,...,68,65,35,7,No information,No information,11,5,2,0
36,https://www.sofascore.com/poland-albania/PTbsd...,Albania,Poland,"02/09/2021, 11:45",61%,39%,1,1,12,7,...,65,68,7,35,No information,No information,5,11,1,4
37,https://www.sofascore.com/poland-albania/PTbsd...,Albania,Poland,"12/10/2021, 11:45",39%,61%,1,1,7,12,...,68,65,35,7,No information,No information,11,5,1,0
38,https://www.sofascore.com/qatar-albania/PTbsRV...,Albania,Qatar,"09/11/2022, 09:30",No information,No information,No information,No information,7,7,...,No information,No information,No information,No information,No information,No information,3,8,1,0
39,https://www.sofascore.com/san-marino-albania/P...,Albania,San marino,"31/03/2021, 11:45",28%,72%,0,6,0,25,...,No information,No information,41,1,No information,No information,12,3,0,2
40,https://www.sofascore.com/san-marino-albania/P...,Albania,San marino,"08/09/2021, 11:45",72%,28%,6,0,25,0,...,No information,No information,1,41,No information,No information,3,12,5,0
41,https://www.sofascore.com/spain-albania/PTbsYT...,Albania,Spain,"26/03/2022, 11:45",28%,72%,No information,No information,4,15,...,No information,No information,No information,No information,No information,No information,5,2,1,2
42,https://www.sofascore.com/turkey-albania/PTbsa...,Albania,Türkiye,"22/03/2019, 12:45",59%,41%,2,1,15,8,...,No information,No information,10,15,No information,No information,4,12,2,0
43,https://www.sofascore.com/wales-albania/PTbscU...,Albania,Wales,"05/06/2021, 09:00",42%,58%,No information,No information,2,5,...,No information,No information,No information,No information,No information,No information,10,6,0,0

In [26]:
# putting all of the documents into Game Stats Cleaned:

input_dir = '/Users/grealish/Desktop/Euros Prediction Model/EuroPrediction/Game Statistics'
output_dir = '/Users/grealish/Desktop/Euros Prediction Model/EuroPrediction/Game Stats Cleaned'

#team names without turkey
team_names = ['Austria','Belgium','Croatia','Czechia','Denmark','England','France','Georgia','Germany','Hungary','Italy','Netherlands',
              'Poland','Portugal','Romania','Scotland','Serbia','Slovakia','Slovenia','Spain','Switzerland','Ukraine'] 

for team in team_names:
    file_path = os.path.join(input_dir, f'{team}_ALL.csv')

    output_file = os.path.join(output_dir,f'{team}_Combined_Performance.csv')
    try:
        combine_game_stats(file_path,team,output_file)
        print(f'Processed {team} successfully.')
    except FileNotFoundError:
        print(f'File for {team} not found. Skipping...')
    except Exception as e:
        print(f'An error occurred while prcessing {team}: {e}')

Processed Austria successfully.
Processed Belgium successfully.
Processed Croatia successfully.
Processed Czechia successfully.
Processed Denmark successfully.
Processed England successfully.
Processed France successfully.
Processed Georgia successfully.
Processed Germany successfully.
Processed Hungary successfully.
Processed Italy successfully.
Processed Netherlands successfully.
Processed Poland successfully.
Processed Portugal successfully.
Processed Romania successfully.
Processed Scotland successfully.
Processed Serbia successfully.
Processed Slovakia successfully.
Processed Slovenia successfully.
Processed Spain successfully.
Processed Switzerland successfully.
Processed Ukraine successfully.

In [27]:
# testing the cleaned 

germany = pd.read_csv('/Users/grealish/Desktop/Euros Prediction Model/EuroPrediction/Game Stats Cleaned/Germany_Combined_Performance.csv')

germany

,Game Link,Target Team,Opponent,Date,Ball possession For,Ball possession Against,Big chances For,Big chances Against,Total shots For,Total shots Against,...,Recoveries For,Recoveries Against,Clearances For,Clearances Against,Goals prevented For,Goals prevented Against,Goal kicks For,Goal kicks Against,Goals For,Goals Against
0,https://www.sofascore.com/armenia-germany/lUbs...,Germany,Armenia,"05/09/2021, 11:45",26%,74%,1,5,4,20,...,No information,No information,19,7,No information,No information,15,3,6,0
1,https://www.sofascore.com/armenia-germany/lUbs...,Germany,Armenia,"14/11/2021, 09:00",74%,26%,5,1,20,4,...,No information,No information,7,19,No information,No information,3,15,1,4
2,https://www.sofascore.com/austria-germany/lUbs...,Germany,Austria,"21/11/2023, 11:45",56%,44%,0,3,8,16,...,63,67,20,16,No information,No information,12,9,0,2
3,https://www.sofascore.com/belarus-germany/lUbs...,Germany,Belarus,"16/11/2019, 11:45",71%,29%,3,3,31,13,...,No information,No information,4,38,No information,No information,5,18,4,0
4,https://www.sofascore.com/belgium-germany/lUbs...,Germany,Belgium,"28/03/2023, 11:45",54%,46%,3,4,16,7,...,No information,No information,5,30,No information,No information,1,14,3,2
5,https://www.sofascore.com/colombia-germany/lUb...,Germany,Colombia,"20/06/2023, 11:45",62%,38%,0,3,4,10,...,44,53,3,16,No information,No information,9,6,2,0
6,https://www.sofascore.com/costa-rica-germany/l...,Germany,Costa rica,"01/12/2022, 11:00",68%,32%,10,3,32,8,...,No information,No information,9,42,0.61,1.04,2,14,2,4
7,https://www.sofascore.com/czech-republic-germa...,Germany,Czechia,"11/11/2020, 11:45",55%,45%,No information,No information,13,12,...,No information,No information,No information,No information,No information,No information,11,8,1,0
8,https://www.sofascore.com/england-germany/lUbs...,Germany,England,"07/06/2022, 11:45",41%,59%,3,2,13,10,...,No information,No information,16,15,No information,No information,6,8,1,1
9,https://www.sofascore.com/england-germany/lUbs...,Germany,England,"26/09/2022, 11:45",59%,41%,2,3,10,13,...,No information,No information,15,16,No information,No information,8,6,3,3
10,https://www.sofascore.com/england-germany/lUbs...,Germany,England,"29/06/2021, 09:00",59%,41%,2,3,10,13,...,No information,No information,15,16,No information,No information,8,6,0,2
11,https://www.sofascore.com/germany-denmark/BObs...,Germany,Denmark,"02/06/2021, 12:00",54%,46%,No information,No information,10,3,...,No information,No information,No information,No information,No information,No information,7,9,1,1
12,https://www.sofascore.com/germany-france/GObsl...,Germany,France,"12/09/2023, 12:00",42%,58%,2,2,11,15,...,56,60,14,14,No information,No information,10,11,2,1
13,https://www.sofascore.com/germany-france/GObsl...,Germany,France,"23/03/2024, 13:00",58%,42%,2,2,15,11,...,60,56,14,14,No information,No information,11,10,0,2
14,https://www.sofascore.com/germany-france/GObsl...,Germany,France,"15/06/2021, 12:00",58%,42%,2,2,15,11,...,60,56,14,14,No information,No information,11,10,0,1
15,https://www.sofascore.com/germany-greece/kUbsl...,Germany,Greece,"07/06/2024, 11:45",69%,31%,1,4,12,14,...,42,39,13,32,No information,No information,3,8,2,1
16,https://www.sofascore.com/germany-hungary/jUbs...,Germany,Hungary,"23/09/2022, 11:45",70%,30%,3,4,19,11,...,41,32,20,31,1.08,1.16,3,11,1,0
17,https://www.sofascore.com/germany-hungary/jUbs...,Germany,Hungary,"19/06/2024, 09:00",70%,30%,3,4,19,11,...,41,32,20,31,1.08,1.16,3,11,2,0
18,https://www.sofascore.com/germany-hungary/jUbs...,Germany,Hungary,"23/06/2021, 12:00",70%,30%,3,4,19,11,...,41,32,20,31,1.08,1.16,3,11,2,2
19,https://www.sofascore.com/germany-iceland/iUbs...,Germany,Iceland,"25/03/2021, 12:45",29%,71%,0,5,4,19,...,No information,No information,18,3,No information,No information,12,2,3,0
20,https://www.sofascore.com/germany-iceland/iUbs...,Germany,Iceland,"08/09/2021, 11:45",71%,29%,5,0,19,4,...,No information,No information,3,18,No information,No information,2,12,0,4
21,https://www.sofascore.com/germany-israel/FObsl...,Germany,Israel,"26/03/2022, 12:45",72%,28%,No information,No information,19,3,...,No information,No information,No information,No information,No information,No information,5,15,2,0
22,https://www.sofascore.com/germany-italy/hUbslU...,Germany,Italy,"14/06/2022, 11:45",65%,35%,6,3,17,14,...,No information,No information,11,20,No information,No information,8,6,5,2
23,https://www.sofascore.com/germany-italy/hUbslU...,Germany,Italy,"04/06/2022, 11:45",35%,65%,3,6,14,17,...,No information,No information,20,11,No information,No information,6,8,1,1
24,https://www.sofascore.com/germany-latvia/gUbsl...,Germany,Latvia,"07/06/2021, 11:45",72%,28%,No information,No information,19,3,...,No information,No information,No information,No information,No information,No information,1,20,7,1
25,https://www.sofascore.com/germany-netherlands/...,Germany,Netherlands,"29/03/2022, 11:45",59%,41%,No information,No information,14,9,...,No information,No information,No information,No information,No information,No information,7,12,1,1
26,https://www.sofascore.com/germany-netherlands/...,Germany,Netherlands,"26/03/2024, 12:45",62%,38%,2,1,11,9,...,43,41,11,8,No information,No information,5,5,2,1
27,https://www.sofascore.com/germany-poland/dUblU...,Germany,Poland,"16/06/2023, 11:45",76%,24%,1,0,26,2,...,48,48,6,29,No information,No information,0,10,0,1
28,https://www.sofascore.com/germany-portugal/eUb...,Germany,Portugal,"19/06/2021, 09:00",57%,43%,3,2,12,7,...,No information,No information,15,16,-0.09,-1.69,5,7,2,4
29,https://www.sofascore.com/germany-romania/CObs...,Germany,Romania,"28/03/2021, 11:45",23%,77%,1,3,9,22,...,No information,No information,30,6,No information,No information,16,7,0,1
30,https://www.sofascore.com/germany-romania/CObs...,Germany,Romania,"08/10/2021, 11:45",77%,23%,3,1,22,9,...,No information,No information,6,30,No information,No information,7,16,2,1
31,https://www.sofascore.com/germany-scotland/VTb...,Germany,Scotland,"14/06/2024, 12:00",73%,27%,1,0,20,1,...,45,34,16,22,-1.00,-1.67,2,10,5,1
32,https://www.sofascore.com/germany-spain/YTbslU...,Germany,Spain,"27/11/2022, 11:00",36%,64%,2,1,11,7,...,No information,No information,11,13,0.32,0.76,5,9,1,1
33,https://www.sofascore.com/germany-spain/YTbslU...,Germany,Spain,"17/11/2020, 11:45",36%,64%,2,1,11,7,...,No information,No information,11,13,0.32,0.76,5,9,0,6
34,https://www.sofascore.com/germany-turkey/aUbsl...,Germany,Türkiye,"18/11/2023, 11:45",55%,45%,4,3,11,8,...,61,55,15,16,No information,No information,4,4,3,2
35,https://www.sofascore.com/germany-ukraine/bUbs...,Germany,Ukraine,"12/06/2023, 09:00",62%,38%,2,0,27,6,...,48,38,13,37,No information,No information,2,14,3,3
36,https://www.sofascore.com/germany-ukraine/bUbs...,Germany,Ukraine,"03/06/2024, 11:45",62%,38%,2,0,27,6,...,48,38,13,37,No information,No information,2,14,0,0
37,https://www.sofascore.com/germany-ukraine/bUbs...,Germany,Ukraine,"14/11/2020, 11:45",62%,38%,2,0,27,6,...,48,38,13,37,No information,No information,2,14,3,1
38,https://www.sofascore.com/japan-germany/lUbsvV...,Germany,Japan,"23/11/2022, 05:00",67%,33%,1,3,11,14,...,46,52,4,17,No information,No information,4,8,2,1
39,https://www.sofascore.com/japan-germany/lUbsvV...,Germany,Japan,"09/09/2023, 11:45",67%,33%,1,3,11,14,...,46,52,4,17,No information,No information,4,8,4,1
40,https://www.sofascore.com/liechtenstein-german...,Germany,Liechtenstein,"02/09/2021, 11:45",18%,82%,0,11,4,42,...,No information,No information,48,0,No information,No information,21,2,0,2
41,https://www.sofascore.com/liechtenstein-german...,Germany,Liechtenstein,"11/11/2021, 11:45",82%,18%,11,0,42,4,...,No information,No information,0,48,No information,No information,2,21,9,0
42,https://www.sofascore.com/mexico-germany/lUbsG...,Germany,Mexico,"17/10/2023, 17:00",68%,32%,5,2,9,12,...,49,45,12,10,No information,No information,7,7,2,2
43,https://www.sofascore.com/north-macedonia-germ...,Germany,North macedonia,"31/03/2021, 11:45",26%,74%,1,6,7,24,...,No information,No information,26,7,No information,No information,11,5,2,1
44,https://www.sofascore.com/north-macedonia-germ...,Germany,North macedonia,"11/10/2021, 11:45",74%,26%,6,1,24,7,...,No information,No information,7,26,No information,No information,5,11,0,4
45,https://www.sofascore.com/northern-ireland-ger...,Germany,Northern ireland,"19/11/2019, 11:45",72%,28%,2,0,22,7,...,No information,No information,13,20,No information,No information,2,7,6,1
46,https://www.sofascore.com/oman-germany/lUbsMVb...,Germany,Oman,"11/16/2022, 17:00",71%,29%,4,1,19,7,...,No information,No information,8,20,No information,No information,5,8,0,1
47,https://www.sofascore.com/peru-germany/lUbsPVb...,Germany,Peru,"25/03/2023, 12:45",66%,34%,6,0,17,2,...,No information,No information,8,21,No information,No information,6,8,2,0
48,https://www.sofascore.com/usa-germany/lUbszUb#...,Germany,Usa,"14/10/2023, 12:00",60%,40%,5,1,19,6,...,54,49,14,20,No information,No information,6,9,1,3